name: Release
on:
  push:
    tags:
      - '*'

jobs:
  # Job: Create release
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      # Check if tag is valid
      - name: Check tag
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      # Create release
      - name: Create release
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1.18.0
        with:
          generateReleaseNotes: true

  # Job: Publish on TER
#  ter-publish:
#    if: startsWith(github.ref, 'refs/tags/')
#    needs: [ release ]
#    runs-on: ubuntu-latest
#    env:
#      TYPO3_EXTENSION_KEY: typo3_stream_writer
#      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}
#      TYPO3_EXCLUDE_FROM_PACKAGING: packaging_exclude.php
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      # Check if tag is valid
#      - name: Check tag
#        run: |
#          if ! [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
#            exit 1
#          fi
#
#      # Prepare version
#      - id: get-version
#        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
#      - id: get-comment
#        run: echo "comment=See release notes at ${{ needs.release.outputs.release-notes-url }}" >> $GITHUB_OUTPUT
#
#      # Prepare environment
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 8.4
#          extensions: intl, mbstring, json, zip, curl
#          tools: composer:v2, typo3/tailor
#
#      - name: Reset files
#        run: git reset --hard HEAD && git clean -dfx
#
#      # Release
#      - name: Publish to TER
#        run: |
#          php ~/.composer/vendor/bin/tailor set-version "${{ steps.get-version.outputs.version }}" --no-docs
#          php ~/.composer/vendor/bin/tailor ter:publish --comment "${{ steps.get-comment.outputs.comment }}" "${{ steps.get-version.outputs.version }}"
